version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .envcc
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .envcc
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-data:
